import { createSignal, onCleanup, onMount, Show, For, createMemo } from "solid-js";
import { getController } from "../audio/controller";
import { decodeAudio } from "../audio/decode";
import { encodeWavPcm16 } from "../audio/wav-encode";
import { detectTempo } from "../ai/tempo";
import { buildWaveform, type Waveform } from "../audio/waveform-cache";
import { createProjectStore } from "../project/store";
import { Timeline, type ClipRef, type ClipPatch } from "./timeline/Timeline";
import { AiPanel } from "./ai/AiPanel";
import { RecordButton } from "./RecordButton";
import { ModeBar, type EditMode } from "./ModeBar";
import { Inspector } from "./Inspector";
import { opfsAvailable, saveProject, loadProject, listProjects } from "../project/opfs";

export function App() {
  const [playing, setPlaying] = createSignal(false);
  const [position, setPosition] = createSignal(0);
  const [error, setError] = createSignal<string | null>(null);
  const [busy, setBusy] = createSignal(false);
  const [projects, setProjects] = createSignal<Array<{ id: string; name: string; modifiedAt: string }>>([]);

  const project = createProjectStore();
  // sourceId → Waveform (main thread cache for rendering)
  const [waveforms, setWaveforms] = createSignal<Map<number, Waveform>>(new Map());
  // sourceId → raw audio bytes (for OPFS save)
  const sourceBytes = new Map<number, ArrayBuffer>();
  // engine track id ↔ project track id mapping
  const engineTrackIds = new Map<number, number>();
  const engineSourceIds = new Map<number, number>();
  // projClipId → engineClipId. Updated on every move/trim since the engine
  // re-adds the clip (no in-place update API), assigning a new id each time.
  const engineClipIds = new Map<number, number>();

  const [selectedClip, setSelectedClip] = createSignal<ClipRef | null>(null);
  const [selectedTrack, setSelectedTrack] = createSignal<number | null>(null);
  const [mode, setMode] = createSignal<EditMode>("move");
  // Persist between reloads so users don't have to recollapse every visit.
  const [headerCollapsed, setHeaderCollapsed] = createSignal(
    typeof localStorage !== "undefined" && localStorage.getItem("trippy:headerCollapsed") === "1",
  );
  function toggleHeader() {
    const next = !headerCollapsed();
    setHeaderCollapsed(next);
    try {
      localStorage.setItem("trippy:headerCollapsed", next ? "1" : "0");
    } catch {
      /* private-browsing or storage disabled — non-fatal */
    }
  }
  // Inspector visibility is decoupled from selection. Tapping a clip selects
  // it (visual highlight only) — the Inspector opens only on long-press or
  // when the user taps the small "details" pill. This keeps the touch zone
  // clear during routine moves.
  const [inspectorOpen, setInspectorOpen] = createSignal(false);
  // A pending tempo suggestion surfaced after a clip is imported with a
  // confident BPM estimate. User can adopt or dismiss.
  const [tempoSuggestion, setTempoSuggestion] = createSignal<
    { bpm: number; sourceLabel: string } | null
  >(null);
  // Tracks whether the user has manually set the project BPM — we only
  // *auto*-adopt detected tempo on the very first import.
  let bpmIsUserSet = false;

  // Resolve the currently-selected clip into concrete track + clip snapshots
  // for the Inspector. Returns null if nothing matches.
  const selectedClipDetail = createMemo(() => {
    const sel = selectedClip();
    if (!sel) return null;
    const t = project.state.project.tracks.find((tr) => tr.id === sel.trackId);
    const c = t?.clips.find((cl) => cl.id === sel.clipId);
    if (!t || !c) return null;
    return { track: t, clip: c };
  });
  const selectedTrackSnap = createMemo(() => {
    const id = selectedTrack();
    if (id == null) return null;
    return project.state.project.tracks.find((t) => t.id === id) ?? null;
  });

  const controller = getController();

  onMount(() => {
    const unsub = controller.onTransportChange((s) => {
      setPosition(s.positionFrames);
      setPlaying(s.playing);
    });
    onCleanup(unsub);
    refreshProjectList();
  });

  async function refreshProjectList() {
    if (!opfsAvailable()) return;
    try {
      setProjects(await listProjects());
    } catch (e) {
      console.warn("listProjects failed", e);
    }
  }

  // Distil a long file name (or our internal "recording-2026-...-...-.." prefix
  // generated by RecordButton) down to a short, distinct label the mixer strip
  // can show without clipping. Recordings get an incrementing "rec N" name
  // numbered across the current session, so multiple takes never collide on
  // identical-looking timestamp prefixes.
  function friendlyTrackName(file: File): string {
    if (file.name.startsWith("recording-")) {
      const existing = project.state.project.tracks.filter((t) =>
        /^rec \d+$/.test(t.name),
      ).length;
      return `rec ${existing + 1}`;
    }
    const stem = file.name.replace(/\.[^.]+$/, "");
    return stem.length > 22 ? `${stem.slice(0, 21)}…` : stem;
  }

  async function loadFile(file: File) {
    setError(null);
    setBusy(true);
    try {
      await controller.resume();
      const rawBytes = await file.arrayBuffer();

      // 1) Decode the file via the browser. Handles wav, mp3, m4a (iOS
      //    Voice Memos), flac, ogg — anything the host AudioContext
      //    understands. The engine only ingests WAV, so we re-encode after.
      const decoded = await decodeAudio(rawBytes);

      // 2) Re-encode to 16-bit PCM WAV in memory. Cheap and keeps the
      //    project bundle on disk format-uniform.
      const wavBytes = encodeWavPcm16(decoded.channels, decoded.sampleRate);

      // 3) Send the WAV to the engine worker for playback
      const engineSrc = await controller.loadWav(wavBytes);

      // 4) Build waveform peaks for the timeline
      const wf = buildWaveform(decoded.channels, decoded.sampleRate);

      // 5) Register in the project model. Save the re-encoded WAV (not
      //    rawBytes) so reload uses the same canonical bytes — m4a files
      //    don't survive a project export to another browser/runtime.
      const projSourceId = (project.state.project.sources.at(-1)?.id ?? 0) + 1;
      project.addSource({
        id: projSourceId,
        file: `src-${projSourceId}.wav`,
        sampleRate: engineSrc.sampleRate,
        channels: engineSrc.channels,
        frameCount: engineSrc.frameCount,
        originalName: file.name,
      });
      engineSourceIds.set(projSourceId, engineSrc.sourceId);
      sourceBytes.set(projSourceId, wavBytes);
      setWaveforms((m) => {
        const next = new Map(m);
        next.set(projSourceId, wf);
        return next;
      });

      // 4) Create track + clip
      const friendly = friendlyTrackName(file);
      const projTrackId = project.addTrack(friendly);
      const engineTrackId = await controller.addTrack();
      engineTrackIds.set(projTrackId, engineTrackId);

      const clipId = project.addClip(projTrackId, {
        sourceId: projSourceId,
        startFrame: 0,
        lengthFrames: engineSrc.frameCount,
        offsetInSource: 0,
        gain: 1,
        label: friendly,
      });
      if (clipId != null) {
        const engineClipId = await controller.addClip({
          trackId: engineTrackId,
          sourceId: engineSrc.sourceId,
          startFrame: 0,
          lengthFrames: engineSrc.frameCount,
          offsetInSource: 0,
        });
        engineClipIds.set(clipId, engineClipId);
      }

      // 5) Auto-set loop on first load to the new clip
      if (project.state.project.tracks.length === 1) {
        controller.setLoop(0, engineSrc.frameCount);
        project.setLoop({ start: 0, end: engineSrc.frameCount });
      }

      // 6) Detect tempo. Cheap on a Float32Array we already have decoded.
      //    Run it after the UI work above so the user sees the clip land
      //    immediately and the BPM banner pops in a beat later.
      queueMicrotask(() => {
        const t = detectTempo(decoded.channels, decoded.sampleRate);
        if (t.confidence < 0.25) return;
        const projBpm = project.state.project.transport.bpm;
        const isFirstClip = project.state.project.tracks.length === 1;
        const rounded = Math.round(t.bpm);
        // Auto-adopt only on the first import and only if the user hasn't
        // typed a BPM. Otherwise surface as a dismissible suggestion.
        if (isFirstClip && !bpmIsUserSet) {
          project.setBpm(rounded);
          controller.setBpm(rounded);
          return;
        }
        if (Math.abs(rounded - projBpm) >= 1) {
          setTempoSuggestion({ bpm: rounded, sourceLabel: friendly });
        }
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }

  async function togglePlay() {
    await controller.resume();
    if (playing()) controller.stop();
    else controller.play();
  }

  async function save() {
    setError(null);
    setBusy(true);
    try {
      await saveProject(project.state.project, sourceBytes);
      project.markClean();
      await refreshProjectList();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  async function load(id: string) {
    setError(null);
    setBusy(true);
    try {
      const { project: proj, sourceBytes: bytes } = await loadProject(id);
      project.replace(proj);
      sourceBytes.clear();
      engineSourceIds.clear();
      engineTrackIds.clear();
      engineClipIds.clear();
      setSelectedClip(null);
      const newWf = new Map<number, Waveform>();
      // Re-push all sources to engine + rebuild waveforms
      for (const src of proj.sources) {
        const b = bytes.get(src.id);
        if (!b) continue;
        sourceBytes.set(src.id, b);
        const engineSrc = await controller.loadWav(b);
        engineSourceIds.set(src.id, engineSrc.sourceId);
        const decoded = await decodeAudio(b);
        newWf.set(src.id, buildWaveform(decoded.channels, decoded.sampleRate));
      }
      setWaveforms(newWf);
      // Re-create tracks + clips on the engine
      for (const t of proj.tracks) {
        const engineTid = await controller.addTrack();
        engineTrackIds.set(t.id, engineTid);
        controller.setTrackGain(engineTid, t.gain);
        controller.setTrackPan(engineTid, t.pan);
        controller.setTrackMute(engineTid, t.mute);
        controller.setTrackSolo(engineTid, t.solo);
        for (const c of t.clips) {
          const engineSid = engineSourceIds.get(c.sourceId);
          if (engineSid == null) continue;
          const eid = await controller.addClip({
            trackId: engineTid,
            sourceId: engineSid,
            startFrame: c.startFrame,
            lengthFrames: c.lengthFrames,
            offsetInSource: c.offsetInSource,
          });
          engineClipIds.set(c.id, eid);
        }
      }
      if (proj.transport.loop) {
        controller.setLoop(proj.transport.loop.start, proj.transport.loop.end);
      } else {
        controller.clearLoop();
      }
      controller.setBpm(proj.transport.bpm);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  function fmtTime(n: number): string {
    if (controller.sampleRate <= 0) return `${n}f`;
    const secs = n / controller.sampleRate;
    const m = Math.floor(secs / 60);
    const s = (secs % 60).toFixed(2);
    return `${m}:${s.padStart(5, "0")}`;
  }

  const bpm = createMemo(() => project.state.project.transport.bpm);

  // Re-add the engine-side clip after a project-side mutation. The engine has
  // no in-place update, so we tear down and recreate; the worker preserves
  // monotonic clip ids so we map the fresh id back into engineClipIds.
  async function resyncClipToEngine(trackId: number, clipId: number) {
    const oldEngineClip = engineClipIds.get(clipId);
    const oldEngineTrack = engineTrackIds.get(trackId);
    // The project model already reflects the post-edit state — find the clip
    // (it may have moved to a different track).
    let projTrack: { id: number } | undefined;
    let projClip:
      | { id: number; sourceId: number; startFrame: number; lengthFrames: number; offsetInSource: number }
      | undefined;
    for (const t of project.state.project.tracks) {
      const c = t.clips.find((cl) => cl.id === clipId);
      if (c) {
        projTrack = t;
        projClip = c;
        break;
      }
    }
    if (!projTrack || !projClip) return;
    const newEngineTrack = engineTrackIds.get(projTrack.id);
    if (newEngineTrack == null) return;
    const engineSrc = engineSourceIds.get(projClip.sourceId);
    if (engineSrc == null) return;

    if (oldEngineTrack != null && oldEngineClip != null) {
      controller.removeClip(oldEngineTrack, oldEngineClip);
    }
    const newId = await controller.addClip({
      trackId: newEngineTrack,
      sourceId: engineSrc,
      startFrame: projClip.startFrame,
      lengthFrames: projClip.lengthFrames,
      offsetInSource: projClip.offsetInSource,
    });
    engineClipIds.set(clipId, newId);
  }

  function handleClipChange(ref: ClipRef, patch: ClipPatch) {
    const movingTrack = patch.trackId != null && patch.trackId !== ref.trackId;
    if (movingTrack) {
      // Find the clip on its current track, copy it onto the destination, then
      // remove from the original. Reuses the same clipId for engineClipIds.
      const fromTrack = project.state.project.tracks.find((t) => t.id === ref.trackId);
      const clip = fromTrack?.clips.find((c) => c.id === ref.clipId);
      if (!clip) return;
      project.commit((p) => {
        const ft = p.tracks.find((t) => t.id === ref.trackId);
        const tt = p.tracks.find((t) => t.id === patch.trackId);
        if (!ft || !tt) return;
        const idx = ft.clips.findIndex((c) => c.id === ref.clipId);
        if (idx < 0) return;
        const [moved] = ft.clips.splice(idx, 1);
        if (!moved) return;
        if (patch.startFrame != null) moved.startFrame = patch.startFrame;
        if (patch.lengthFrames != null) moved.lengthFrames = patch.lengthFrames;
        if (patch.offsetInSource != null) moved.offsetInSource = patch.offsetInSource;
        tt.clips.push(moved);
      });
      void resyncClipToEngine(patch.trackId!, ref.clipId);
    } else {
      project.updateClip(ref.trackId, ref.clipId, {
        ...(patch.startFrame != null && { startFrame: patch.startFrame }),
        ...(patch.lengthFrames != null && { lengthFrames: patch.lengthFrames }),
        ...(patch.offsetInSource != null && { offsetInSource: patch.offsetInSource }),
      });
      void resyncClipToEngine(ref.trackId, ref.clipId);
    }
  }

  function deleteClip(ref: ClipRef) {
    const eTrack = engineTrackIds.get(ref.trackId);
    const eClip = engineClipIds.get(ref.clipId);
    if (eTrack != null && eClip != null) controller.removeClip(eTrack, eClip);
    engineClipIds.delete(ref.clipId);
    project.removeClip(ref.trackId, ref.clipId);
    setSelectedClip(null);
    setInspectorOpen(false);
  }

  // Cut a clip into two at `splitFrame` (project time). Left half retains
  // the original projClipId & engine clip; the right half is a fresh clip
  // starting at splitFrame with an offsetInSource that keeps audio aligned.
  async function splitClipAt(ref: ClipRef, splitFrame: number) {
    const track = project.state.project.tracks.find((t) => t.id === ref.trackId);
    const clip = track?.clips.find((c) => c.id === ref.clipId);
    if (!track || !clip) return;
    const clipEnd = clip.startFrame + clip.lengthFrames;
    if (splitFrame <= clip.startFrame + 64 || splitFrame >= clipEnd - 64) return;

    const leftLength = splitFrame - clip.startFrame;
    const rightOffset = clip.offsetInSource + leftLength;
    const rightLength = clip.lengthFrames - leftLength;

    // 1) Shorten the left (existing) clip in the project model & engine.
    project.updateClip(ref.trackId, ref.clipId, { lengthFrames: leftLength });
    await resyncClipToEngine(ref.trackId, ref.clipId);

    // 2) Create the right-half clip.
    const newProjClipId = project.addClip(ref.trackId, {
      sourceId: clip.sourceId,
      startFrame: splitFrame,
      lengthFrames: rightLength,
      offsetInSource: rightOffset,
      gain: clip.gain,
      label: clip.label,
    });
    if (newProjClipId == null) return;
    const eTrack = engineTrackIds.get(ref.trackId);
    const eSrc = engineSourceIds.get(clip.sourceId);
    if (eTrack != null && eSrc != null) {
      const eid = await controller.addClip({
        trackId: eTrack,
        sourceId: eSrc,
        startFrame: splitFrame,
        lengthFrames: rightLength,
        offsetInSource: rightOffset,
      });
      engineClipIds.set(newProjClipId, eid);
    }
  }

  function splitSelectedAtPlayhead() {
    const sel = selectedClip();
    if (!sel) return;
    void splitClipAt(sel, position());
  }

  function setClipGain(ref: ClipRef, gain: number) {
    project.updateClip(ref.trackId, ref.clipId, { gain });
    // Note: engine doesn't yet honor per-clip gain; this is project metadata
    // until the engine grows a clip-gain field. The slider still updates the
    // saved value so it lights up correctly when the engine catches up.
  }

  function renameClip(ref: ClipRef, label: string) {
    project.updateClip(ref.trackId, ref.clipId, { label });
  }

  function addEmptyTrack() {
    const projTrackId = project.addTrack(`track ${project.state.project.tracks.length + 1}`);
    void (async () => {
      const eid = await controller.addTrack();
      engineTrackIds.set(projTrackId, eid);
    })();
    setSelectedTrack(projTrackId);
    setSelectedClip(null);
  }

  function renameTrack(trackId: number, name: string) {
    project.updateTrack(trackId, { name });
  }

  function colorTrack(trackId: number, color: string) {
    project.updateTrack(trackId, { color });
  }

  function deleteTrack(trackId: number) {
    const eTrack = engineTrackIds.get(trackId);
    const track = project.state.project.tracks.find((t) => t.id === trackId);
    // Drop engine clip-id mappings for any clip on this track first.
    if (track) for (const c of track.clips) engineClipIds.delete(c.id);
    if (eTrack != null) controller.removeTrack(eTrack);
    engineTrackIds.delete(trackId);
    project.removeTrack(trackId);
    setSelectedTrack(null);
    setSelectedClip(null);
    setInspectorOpen(false);
  }

  // Render the project to a downloadable WAV. Bounds the render to the last
  // clip's end frame so we don't burn cycles on empty tail.
  async function exportProject() {
    setError(null);
    setBusy(true);
    try {
      let lastFrame = 0;
      for (const t of project.state.project.tracks) {
        for (const c of t.clips) {
          const end = c.startFrame + c.lengthFrames;
          if (end > lastFrame) lastFrame = end;
        }
      }
      if (lastFrame <= 0) {
        setError("Nothing to export — add at least one clip first.");
        return;
      }
      // Add ~250ms of tail so reverb / delay decays aren't chopped off.
      const tail = Math.floor(controller.sampleRate * 0.25);
      const total = lastFrame + tail;

      const { interleaved, sampleRate } = await controller.renderOffline(total);
      // Deinterleave into L/R for the WAV encoder.
      const frames = interleaved.length / 2;
      const l = new Float32Array(frames);
      const r = new Float32Array(frames);
      for (let i = 0; i < frames; i++) {
        l[i] = interleaved[i * 2]!;
        r[i] = interleaved[i * 2 + 1]!;
      }
      const wav = encodeWavPcm16([l, r], sampleRate);
      const blob = new Blob([wav], { type: "audio/wav" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      const safeName = project.state.project.meta.name.replace(/[^\w.-]+/g, "_") || "trippy";
      a.href = url;
      a.download = `${safeName}.wav`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }

  async function duplicateClip(ref: ClipRef) {
    const track = project.state.project.tracks.find((t) => t.id === ref.trackId);
    const clip = track?.clips.find((c) => c.id === ref.clipId);
    if (!track || !clip) return;
    const newProjClipId = project.addClip(ref.trackId, {
      sourceId: clip.sourceId,
      startFrame: clip.startFrame + clip.lengthFrames,
      lengthFrames: clip.lengthFrames,
      offsetInSource: clip.offsetInSource,
      gain: clip.gain,
      label: clip.label,
    });
    if (newProjClipId == null) return;
    const eTrack = engineTrackIds.get(ref.trackId);
    const eSrc = engineSourceIds.get(clip.sourceId);
    if (eTrack != null && eSrc != null) {
      const eid = await controller.addClip({
        trackId: eTrack,
        sourceId: eSrc,
        startFrame: clip.startFrame + clip.lengthFrames,
        lengthFrames: clip.lengthFrames,
        offsetInSource: clip.offsetInSource,
      });
      engineClipIds.set(newProjClipId, eid);
    }
    setSelectedClip({ trackId: ref.trackId, clipId: newProjClipId });
  }

  return (
    <main
      style={{
        display: "flex",
        "flex-direction": "column",
        height: "100%",
        padding: "env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)",
      }}
    >
      <header
        style={{
          display: "flex",
          "align-items": "center",
          gap: "0.6rem",
          padding: "0.4rem 0.7rem",
          "border-bottom": "1px solid var(--grid)",
          background: "var(--bg-elevated)",
          "flex-wrap": "wrap",
        }}
      >
        {/* Always-visible essentials: collapse toggle, play, position. */}
        <button
          type="button"
          onClick={toggleHeader}
          title={headerCollapsed() ? "Show all controls" : "Hide controls for more track space"}
          aria-expanded={!headerCollapsed()}
          style={{ "min-width": "36px", "min-height": "34px", padding: "0 0.5rem" }}
        >
          {headerCollapsed() ? "▾" : "▴"}
        </button>
        <strong
          style={{
            "letter-spacing": "-0.02em",
            "font-size": "1.05rem",
            display: headerCollapsed() ? "none" : undefined,
          }}
        >
          trippy
        </strong>
        <Show when={!headerCollapsed()}>
          <input
            type="text"
            value={project.state.project.meta.name}
            onInput={(e) => project.rename(e.currentTarget.value)}
            style={{
              background: "var(--bg)",
              color: "var(--fg)",
              border: "1px solid var(--grid)",
              "border-radius": "6px",
              padding: "0.3rem 0.5rem",
              "min-width": "120px",
              flex: "1 1 140px",
              "max-width": "260px",
              font: "inherit",
            }}
          />
        </Show>
        <button onClick={togglePlay} style={{ "min-width": "70px", "min-height": "34px" }}>
          {playing() ? "■ Stop" : "▶ Play"}
        </button>
        <span
          style={{
            "font-family": "ui-monospace, monospace",
            color: "var(--fg-dim)",
            "min-width": "58px",
            "text-align": "right",
            "font-size": "0.85rem",
          }}
        >
          {fmtTime(position())}
        </span>
        <Show when={!headerCollapsed()}>
          <label style={{ display: "flex", "align-items": "center", gap: "0.35rem" }}>
            <span style={{ color: "var(--fg-dim)", "font-size": "0.8rem" }}>BPM</span>
            <input
              type="number"
              min="40"
              max="300"
              step="0.1"
              value={bpm()}
              onChange={(e) => {
                const v = parseFloat(e.currentTarget.value) || 120;
                bpmIsUserSet = true;
                project.setBpm(v);
                controller.setBpm(v);
              }}
              style={{
                width: "70px",
                background: "var(--bg)",
                color: "var(--fg)",
                border: "1px solid var(--grid)",
                "border-radius": "6px",
                padding: "0.35rem 0.45rem",
                font: "inherit",
              }}
            />
          </label>
          <FilePicker onFile={loadFile} disabled={busy()} />
          <RecordButton onRecording={loadFile} onError={setError} disabled={busy()} />
          <button type="button" onClick={addEmptyTrack} title="Add a new empty track">
            + track
          </button>
          <button
            type="button"
            onClick={exportProject}
            disabled={busy() || project.state.project.tracks.length === 0}
            title="Render the project to a WAV file"
          >
            ⤓ Export
          </button>
        </Show>
        <Show when={opfsAvailable() && !headerCollapsed()}>
          <button onClick={save} disabled={busy()} title="Save to browser storage">
            ↓ Save
          </button>
          <Show when={projects().length > 0}>
            <select
              onChange={(e) => {
                const id = e.currentTarget.value;
                if (id) load(id);
                e.currentTarget.value = "";
              }}
              style={{
                background: "var(--bg)",
                color: "var(--fg)",
                border: "1px solid var(--grid)",
                "border-radius": "6px",
                padding: "0.35rem 0.5rem",
                font: "inherit",
                "min-height": "44px",
              }}
            >
              <option value="">Load…</option>
              <For each={projects()}>
                {(p) => <option value={p.id}>{p.name}</option>}
              </For>
            </select>
          </Show>
        </Show>
        <Show when={project.state.dirty}>
          <span style={{ color: "#ffb86b", "font-size": "0.8rem" }}>● unsaved</span>
        </Show>
      </header>

      <Show when={tempoSuggestion()}>
        {(s) => (
          <div
            style={{
              display: "flex",
              "align-items": "center",
              gap: "0.5rem",
              padding: "0.4rem 0.7rem",
              background: "#1c2a1c",
              "border-bottom": "1px solid #2a4a2a",
              "font-size": "0.85rem",
              "flex-wrap": "wrap",
            }}
          >
            <span aria-hidden>♪</span>
            <span style={{ color: "#c0e6c0" }}>
              <em style={{ "font-style": "normal", "font-weight": 600 }}>{s().sourceLabel}</em>
              {" "}looks like{" "}
              <strong style={{ color: "#fff" }}>{s().bpm} BPM</strong>.
            </span>
            <span style={{ flex: 1 }} />
            <button
              type="button"
              onClick={() => {
                bpmIsUserSet = true;
                project.setBpm(s().bpm);
                controller.setBpm(s().bpm);
                setTempoSuggestion(null);
              }}
              style={{ "border-color": "#5cff8c", color: "#c0ffc0", "min-height": "32px" }}
            >
              Use {s().bpm} BPM
            </button>
            <button
              type="button"
              onClick={() => setTempoSuggestion(null)}
              style={{ "min-height": "32px" }}
            >
              Dismiss
            </button>
          </div>
        )}
      </Show>

      <ModeBar mode={mode()} onChange={setMode} />

      {/* Timeline */}
      <section
        style={{
          flex: 1,
          "overflow-y": "auto",
          background: "var(--bg)",
        }}
      >
        <Timeline
          project={project.state.project}
          waveforms={waveforms()}
          positionFrames={position()}
          selected={selectedClip()}
          selectedTrack={selectedTrack()}
          mode={mode()}
          onSeek={(f) => controller.setPosition(f)}
          onSelectClip={(ref) => {
            setSelectedClip(ref);
            if (ref) setSelectedTrack(ref.trackId);
          }}
          onSelectTrack={setSelectedTrack}
          onClipChange={handleClipChange}
          onClipLongPress={(ref) => {
            setSelectedClip(ref);
            setSelectedTrack(ref.trackId);
            setInspectorOpen(true);
          }}
          onClipSlice={(ref, frame) => void splitClipAt(ref, frame)}
          onClipErase={(ref) => deleteClip(ref)}
        />
      </section>

      {/* Mixer strip */}
      <Show when={project.state.project.tracks.length > 0}>
        <section
          style={{
            display: "flex",
            gap: "0.5rem",
            padding: "0.6rem 0.9rem",
            "border-top": "1px solid var(--grid)",
            background: "var(--bg-elevated)",
            "overflow-x": "auto",
          }}
        >
          <For each={project.state.project.tracks}>
            {(t) => (
              <MixerStrip
                name={t.name}
                gain={t.gain}
                pan={t.pan}
                mute={t.mute}
                solo={t.solo}
                onGain={(v) => {
                  project.updateTrack(t.id, { gain: v });
                  const eid = engineTrackIds.get(t.id);
                  if (eid != null) controller.setTrackGain(eid, v);
                }}
                onPan={(v) => {
                  project.updateTrack(t.id, { pan: v });
                  const eid = engineTrackIds.get(t.id);
                  if (eid != null) controller.setTrackPan(eid, v);
                }}
                onMute={(v) => {
                  project.updateTrack(t.id, { mute: v });
                  const eid = engineTrackIds.get(t.id);
                  if (eid != null) controller.setTrackMute(eid, v);
                }}
                onSolo={(v) => {
                  project.updateTrack(t.id, { solo: v });
                  const eid = engineTrackIds.get(t.id);
                  if (eid != null) controller.setTrackSolo(eid, v);
                }}
              />
            )}
          </For>
        </section>
      </Show>

      {/* Floating "details" pill: visible only when something is selected
          and the Inspector is closed. Bottom-right so it doesn't sit under
          the user's finger during a drag. Long-press a clip to skip it. */}
      <Show
        when={
          !inspectorOpen() &&
          (selectedClipDetail() || selectedTrackSnap())
        }
      >
        <button
          type="button"
          onClick={() => setInspectorOpen(true)}
          style={{
            position: "fixed",
            right: "0.9rem",
            bottom: "calc(0.9rem + env(safe-area-inset-bottom))",
            "z-index": 20,
            "min-height": "40px",
            padding: "0 0.85rem",
            "border-radius": "999px",
            background: "var(--accent-dim)",
            "border-color": "var(--accent)",
            color: "var(--fg)",
            "font-weight": 600,
            "box-shadow": "0 4px 14px rgba(0,0,0,0.45)",
          }}
        >
          ⓘ details
        </button>
      </Show>

      <Show when={inspectorOpen()}>
      <Inspector
        selectedClip={selectedClipDetail()}
        selectedTrack={selectedTrackSnap()}
        sampleRate={project.state.project.transport.sampleRate}
        onClipGain={(g) => {
          const s = selectedClip();
          if (s) setClipGain(s, g);
        }}
        onClipDuplicate={() => {
          const s = selectedClip();
          if (s) void duplicateClip(s);
        }}
        onClipDelete={() => {
          const s = selectedClip();
          if (s) deleteClip(s);
        }}
        onClipSplitAtPlayhead={splitSelectedAtPlayhead}
        onClipRename={(label) => {
          const s = selectedClip();
          if (s) renameClip(s, label);
        }}
        onTrackRename={(name) => {
          const id = selectedTrack();
          if (id != null) renameTrack(id, name);
        }}
        onTrackColor={(color) => {
          const id = selectedTrack();
          if (id != null) colorTrack(id, color);
        }}
        onTrackDelete={() => {
          const id = selectedTrack();
          if (id != null) deleteTrack(id);
        }}
        onClose={() => setInspectorOpen(false)}
      />
      </Show>

      <AiPanel
        project={project.state.project}
        onApply={(commands) => {
          for (const c of commands) {
            switch (c.type) {
              case "setTrackGain": {
                const t = project.state.project.tracks.find((tr) => tr.id === c.trackId);
                if (!t) break;
                // The schema sends delta_db; convert to absolute linear gain.
                const newLinear = Math.max(0, t.gain * Math.pow(10, c.gain / 20));
                project.updateTrack(c.trackId, { gain: newLinear });
                const eid = engineTrackIds.get(c.trackId);
                if (eid != null) controller.setTrackGain(eid, newLinear);
                break;
              }
              case "setTrackPan": {
                project.updateTrack(c.trackId, { pan: c.pan });
                const eid = engineTrackIds.get(c.trackId);
                if (eid != null) controller.setTrackPan(eid, c.pan);
                break;
              }
              case "addEq": {
                const eid = engineTrackIds.get(c.trackId);
                if (eid == null) break;
                // The LLM's "kind" parameter is opaque from the engine's
                // perspective until we expand the schema; default to peak.
                void controller.addEq({
                  trackId: eid,
                  freq: c.freq,
                  q: c.q,
                  gainDb: c.gainDb,
                  kind: "peak",
                });
                break;
              }
              case "addCompressor": {
                const eid = engineTrackIds.get(c.trackId);
                if (eid == null) break;
                void controller.addCompressor({
                  trackId: eid,
                  thresholdDb: c.thresholdDb,
                  ratio: c.ratio,
                  attackMs: 10,
                  releaseMs: 100,
                  makeupDb: 0,
                });
                break;
              }
              case "addDelay": {
                const eid = engineTrackIds.get(c.trackId);
                if (eid == null) break;
                void controller.addDelay({
                  trackId: eid,
                  beats: c.beats,
                  feedback: c.feedback,
                  wet: c.wet,
                  pingPong: 0,
                });
                break;
              }
              // Sidechain still needs cross-track signal routing in the engine.
              default:
                break;
            }
          }
        }}
      />

      <Show when={error()}>
        <div
          style={{
            color: "#ff8888",
            "background-color": "#3a1212",
            padding: "0.6rem 0.9rem",
            "border-top": "1px solid #6e2222",
            "font-size": "0.85rem",
          }}
        >
          {error()}
        </div>
      </Show>
    </main>
  );
}

function FilePicker(props: { onFile: (file: File) => void; disabled?: boolean }) {
  let inputRef: HTMLInputElement | undefined;
  return (
    <>
      <input
        ref={(el) => (inputRef = el)}
        type="file"
        // Broad accept so the iOS / Android file picker surfaces Voice
        // Memos (.m4a), recordings, sample libraries — anything an
        // AudioContext can decode. Explicit extensions help platforms
        // that don't honor the wildcard fully.
        accept="audio/*,.wav,.mp3,.m4a,.aac,.flac,.ogg,.opus,.weba"
        style={{ display: "none" }}
        onChange={(e) => {
          const f = e.currentTarget.files?.[0];
          if (f) props.onFile(f);
          e.currentTarget.value = "";
        }}
      />
      <button type="button" disabled={props.disabled} onClick={() => inputRef?.click()}>
        + load
      </button>
    </>
  );
}

function MixerStrip(props: {
  name: string;
  gain: number;
  pan: number;
  mute: boolean;
  solo: boolean;
  onGain: (v: number) => void;
  onPan: (v: number) => void;
  onMute: (v: boolean) => void;
  onSolo: (v: boolean) => void;
}) {
  return (
    <div
      style={{
        background: "var(--bg)",
        border: "1px solid var(--grid)",
        "border-radius": "8px",
        padding: "0.55rem",
        display: "flex",
        "flex-direction": "column",
        gap: "0.35rem",
        "min-width": "100px",
      }}
    >
      <div
        style={{
          "font-size": "0.78rem",
          color: "var(--fg-dim)",
          "white-space": "nowrap",
          overflow: "hidden",
          "text-overflow": "ellipsis",
          "max-width": "90px",
        }}
      >
        {props.name}
      </div>
      <input
        type="range"
        min="0"
        max="1.5"
        step="0.01"
        value={props.gain}
        onInput={(e) => props.onGain(parseFloat(e.currentTarget.value))}
      />
      <input
        type="range"
        min="-1"
        max="1"
        step="0.01"
        value={props.pan}
        onInput={(e) => props.onPan(parseFloat(e.currentTarget.value))}
      />
      <div style={{ display: "flex", gap: "0.3rem" }}>
        <button
          type="button"
          onClick={() => props.onMute(!props.mute)}
          style={{
            flex: 1,
            "min-width": 0,
            "min-height": "30px",
            padding: 0,
            "border-color": props.mute ? "var(--accent)" : "var(--grid)",
            background: props.mute ? "var(--accent-dim)" : "transparent",
            color: props.mute ? "var(--fg)" : "var(--fg-dim)",
            "font-weight": 600,
            "font-size": "0.8rem",
          }}
        >
          M
        </button>
        <button
          type="button"
          onClick={() => props.onSolo(!props.solo)}
          style={{
            flex: 1,
            "min-width": 0,
            "min-height": "30px",
            padding: 0,
            "border-color": props.solo ? "#ffb86b" : "var(--grid)",
            background: props.solo ? "#5a3e1a" : "transparent",
            color: props.solo ? "#ffe6b8" : "var(--fg-dim)",
            "font-weight": 600,
            "font-size": "0.8rem",
          }}
        >
          S
        </button>
      </div>
    </div>
  );
}
