/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmengine_free: (a: number, b: number) => void;
export const _start: () => void;
export const engine_version: () => [number, number];
export const wasmengine_addClip: (a: number, b: number, c: number, d: bigint, e: bigint, f: bigint) => [number, number, number];
export const wasmengine_addSource: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const wasmengine_addSourceFromWav: (a: number, b: number, c: number) => [number, number, number, number];
export const wasmengine_addTrack: (a: number) => number;
export const wasmengine_clearLoop: (a: number) => void;
export const wasmengine_isPlaying: (a: number) => number;
export const wasmengine_new: (a: number) => number;
export const wasmengine_play: (a: number) => void;
export const wasmengine_positionFrames: (a: number) => number;
export const wasmengine_process: (a: number, b: number, c: number, d: any, e: number, f: number, g: any) => [number, number];
export const wasmengine_removeClip: (a: number, b: number, c: number) => number;
export const wasmengine_removeSource: (a: number, b: number) => number;
export const wasmengine_removeTrack: (a: number, b: number) => number;
export const wasmengine_sampleRate: (a: number) => number;
export const wasmengine_setBpm: (a: number, b: number) => void;
export const wasmengine_setLoop: (a: number, b: number, c: number) => void;
export const wasmengine_setPosition: (a: number, b: number) => void;
export const wasmengine_setTrackGain: (a: number, b: number, c: number) => number;
export const wasmengine_setTrackMute: (a: number, b: number, c: number) => number;
export const wasmengine_setTrackPan: (a: number, b: number, c: number) => number;
export const wasmengine_setTrackSolo: (a: number, b: number, c: number) => number;
export const wasmengine_stop: (a: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
